name: build-coached
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello There"
      - name: multiline Command
        run: |
          node -v
          npm -v